package heaps.feathericons;


#if macro
import haxe.macro.Expr;
import haxe.macro.Context;
#end

#if !macro
import heaps.feathericons.utils.GraphicsCommands.GraphicsCommandExecute;
import heaps.feathericons.utils.GraphicsStore;
#end

#if macro
var FeatherIconsEnumFields2Id: Map<String, String> = [
    "activity" => "activity",
    "airplay" => "airplay",
    "alert_circle" => "alert-circle",
    "alert_octagon" => "alert-octagon",
    "alert_triangle" => "alert-triangle",
    "align_center" => "align-center",
    "align_justify" => "align-justify",
    "align_left" => "align-left",
    "align_right" => "align-right",
    "anchor" => "anchor",
    "aperture" => "aperture",
    "archive" => "archive",
    "arrow_down_circle" => "arrow-down-circle",
    "arrow_down_left" => "arrow-down-left",
    "arrow_down_right" => "arrow-down-right",
    "arrow_down" => "arrow-down",
    "arrow_left_circle" => "arrow-left-circle",
    "arrow_left" => "arrow-left",
    "arrow_right_circle" => "arrow-right-circle",
    "arrow_right" => "arrow-right",
    "arrow_up_circle" => "arrow-up-circle",
    "arrow_up_left" => "arrow-up-left",
    "arrow_up_right" => "arrow-up-right",
    "arrow_up" => "arrow-up",
    "at_sign" => "at-sign",
    "award" => "award",
    "bar_chart_2" => "bar-chart-2",
    "bar_chart" => "bar-chart",
    "battery_charging" => "battery-charging",
    "battery" => "battery",
    "bell_off" => "bell-off",
    "bell" => "bell",
    "bluetooth" => "bluetooth",
    "bold" => "bold",
    "book_open" => "book-open",
    "book" => "book",
    "bookmark" => "bookmark",
    "box" => "box",
    "briefcase" => "briefcase",
    "calendar" => "calendar",
    "camera_off" => "camera-off",
    "camera" => "camera",
    "cast_" => "cast",
    "check_circle" => "check-circle",
    "check_square" => "check-square",
    "check" => "check",
    "chevron_down" => "chevron-down",
    "chevron_left" => "chevron-left",
    "chevron_right" => "chevron-right",
    "chevron_up" => "chevron-up",
    "chevrons_down" => "chevrons-down",
    "chevrons_left" => "chevrons-left",
    "chevrons_right" => "chevrons-right",
    "chevrons_up" => "chevrons-up",
    "chrome" => "chrome",
    "circle" => "circle",
    "clipboard" => "clipboard",
    "clock" => "clock",
    "cloud_drizzle" => "cloud-drizzle",
    "cloud_lightning" => "cloud-lightning",
    "cloud_off" => "cloud-off",
    "cloud_rain" => "cloud-rain",
    "cloud_snow" => "cloud-snow",
    "cloud" => "cloud",
    "code" => "code",
    "codepen" => "codepen",
    "codesandbox" => "codesandbox",
    "coffee" => "coffee",
    "columns" => "columns",
    "command" => "command",
    "compass" => "compass",
    "copy" => "copy",
    "corner_down_left" => "corner-down-left",
    "corner_down_right" => "corner-down-right",
    "corner_left_down" => "corner-left-down",
    "corner_left_up" => "corner-left-up",
    "corner_right_down" => "corner-right-down",
    "corner_right_up" => "corner-right-up",
    "corner_up_left" => "corner-up-left",
    "corner_up_right" => "corner-up-right",
    "cpu" => "cpu",
    "credit_card" => "credit-card",
    "crop" => "crop",
    "crosshair" => "crosshair",
    "database" => "database",
    "delete" => "delete",
    "disc" => "disc",
    "divide_circle" => "divide-circle",
    "divide_square" => "divide-square",
    "divide" => "divide",
    "dollar_sign" => "dollar-sign",
    "download_cloud" => "download-cloud",
    "download" => "download",
    "dribbble" => "dribbble",
    "droplet" => "droplet",
    "edit_2" => "edit-2",
    "edit_3" => "edit-3",
    "edit" => "edit",
    "external_link" => "external-link",
    "eye_off" => "eye-off",
    "eye" => "eye",
    "facebook" => "facebook",
    "fast_forward" => "fast-forward",
    "feather" => "feather",
    "figma" => "figma",
    "file_minus" => "file-minus",
    "file_plus" => "file-plus",
    "file_text" => "file-text",
    "file" => "file",
    "film" => "film",
    "filter" => "filter",
    "flag" => "flag",
    "folder_minus" => "folder-minus",
    "folder_plus" => "folder-plus",
    "folder" => "folder",
    "framer" => "framer",
    "frown" => "frown",
    "gift" => "gift",
    "git_branch" => "git-branch",
    "git_commit" => "git-commit",
    "git_merge" => "git-merge",
    "git_pull_request" => "git-pull-request",
    "github" => "github",
    "gitlab" => "gitlab",
    "globe" => "globe",
    "grid" => "grid",
    "hard_drive" => "hard-drive",
    "hash" => "hash",
    "headphones" => "headphones",
    "heart" => "heart",
    "help_circle" => "help-circle",
    "hexagon" => "hexagon",
    "home" => "home",
    "image" => "image",
    "inbox" => "inbox",
    "info" => "info",
    "instagram" => "instagram",
    "italic" => "italic",
    "key" => "key",
    "layers" => "layers",
    "layout" => "layout",
    "life_buoy" => "life-buoy",
    "link_2" => "link-2",
    "link" => "link",
    "linkedin" => "linkedin",
    "list" => "list",
    "loader" => "loader",
    "lock" => "lock",
    "log_in" => "log-in",
    "log_out" => "log-out",
    "mail" => "mail",
    "map_pin" => "map-pin",
    "map" => "map",
    "maximize_2" => "maximize-2",
    "maximize" => "maximize",
    "meh" => "meh",
    "menu" => "menu",
    "message_circle" => "message-circle",
    "message_square" => "message-square",
    "mic_off" => "mic-off",
    "mic" => "mic",
    "minimize_2" => "minimize-2",
    "minimize" => "minimize",
    "minus_circle" => "minus-circle",
    "minus_square" => "minus-square",
    "minus" => "minus",
    "monitor" => "monitor",
    "moon" => "moon",
    "more_horizontal" => "more-horizontal",
    "more_vertical" => "more-vertical",
    "mouse_pointer" => "mouse-pointer",
    "move" => "move",
    "music" => "music",
    "navigation_2" => "navigation-2",
    "navigation" => "navigation",
    "octagon" => "octagon",
    "package_" => "package",
    "paperclip" => "paperclip",
    "pause_circle" => "pause-circle",
    "pause" => "pause",
    "pen_tool" => "pen-tool",
    "percent" => "percent",
    "phone_call" => "phone-call",
    "phone_forwarded" => "phone-forwarded",
    "phone_incoming" => "phone-incoming",
    "phone_missed" => "phone-missed",
    "phone_off" => "phone-off",
    "phone_outgoing" => "phone-outgoing",
    "phone" => "phone",
    "pie_chart" => "pie-chart",
    "play_circle" => "play-circle",
    "play" => "play",
    "plus_circle" => "plus-circle",
    "plus_square" => "plus-square",
    "plus" => "plus",
    "pocket" => "pocket",
    "power" => "power",
    "printer" => "printer",
    "radio" => "radio",
    "refresh_ccw" => "refresh-ccw",
    "refresh_cw" => "refresh-cw",
    "repeat" => "repeat",
    "rewind" => "rewind",
    "rotate_ccw" => "rotate-ccw",
    "rotate_cw" => "rotate-cw",
    "rss" => "rss",
    "save" => "save",
    "scissors" => "scissors",
    "search" => "search",
    "send" => "send",
    "server" => "server",
    "settings" => "settings",
    "share_2" => "share-2",
    "share" => "share",
    "shield_off" => "shield-off",
    "shield" => "shield",
    "shopping_bag" => "shopping-bag",
    "shopping_cart" => "shopping-cart",
    "shuffle" => "shuffle",
    "sidebar" => "sidebar",
    "skip_back" => "skip-back",
    "skip_forward" => "skip-forward",
    "slack" => "slack",
    "slash" => "slash",
    "sliders" => "sliders",
    "smartphone" => "smartphone",
    "smile" => "smile",
    "speaker" => "speaker",
    "square" => "square",
    "star" => "star",
    "stop_circle" => "stop-circle",
    "sun" => "sun",
    "sunrise" => "sunrise",
    "sunset" => "sunset",
    "table" => "table",
    "tablet" => "tablet",
    "tag" => "tag",
    "target" => "target",
    "terminal" => "terminal",
    "thermometer" => "thermometer",
    "thumbs_down" => "thumbs-down",
    "thumbs_up" => "thumbs-up",
    "toggle_left" => "toggle-left",
    "toggle_right" => "toggle-right",
    "tool" => "tool",
    "trash_2" => "trash-2",
    "trash" => "trash",
    "trello" => "trello",
    "trending_down" => "trending-down",
    "trending_up" => "trending-up",
    "triangle" => "triangle",
    "truck" => "truck",
    "tv" => "tv",
    "twitch" => "twitch",
    "twitter" => "twitter",
    "type" => "type",
    "umbrella" => "umbrella",
    "underline" => "underline",
    "unlock" => "unlock",
    "upload_cloud" => "upload-cloud",
    "upload" => "upload",
    "user_check" => "user-check",
    "user_minus" => "user-minus",
    "user_plus" => "user-plus",
    "user_x" => "user-x",
    "user" => "user",
    "users" => "users",
    "video_off" => "video-off",
    "video" => "video",
    "voicemail" => "voicemail",
    "volume_1" => "volume-1",
    "volume_2" => "volume-2",
    "volume_x" => "volume-x",
    "volume" => "volume",
    "watch" => "watch",
    "wifi_off" => "wifi-off",
    "wifi" => "wifi",
    "wind" => "wind",
    "x_circle" => "x-circle",
    "x_octagon" => "x-octagon",
    "x_square" => "x-square",
    "x" => "x",
    "youtube" => "youtube",
    "zap_off" => "zap-off",
    "zap" => "zap",
    "zoom_in" => "zoom-in",
    "zoom_out" => "zoom-out",
];

var FeatherIconsString2Class: Map<String,String> = [
    "activity" => "heaps.feathericons.icons.FeathersIcon_Activity",
    "airplay" => "heaps.feathericons.icons.FeathersIcon_Airplay",
    "alert-circle" => "heaps.feathericons.icons.FeathersIcon_AlertCircle",
    "alert-octagon" => "heaps.feathericons.icons.FeathersIcon_AlertOctagon",
    "alert-triangle" => "heaps.feathericons.icons.FeathersIcon_AlertTriangle",
    "align-center" => "heaps.feathericons.icons.FeathersIcon_AlignCenter",
    "align-justify" => "heaps.feathericons.icons.FeathersIcon_AlignJustify",
    "align-left" => "heaps.feathericons.icons.FeathersIcon_AlignLeft",
    "align-right" => "heaps.feathericons.icons.FeathersIcon_AlignRight",
    "anchor" => "heaps.feathericons.icons.FeathersIcon_Anchor",
    "aperture" => "heaps.feathericons.icons.FeathersIcon_Aperture",
    "archive" => "heaps.feathericons.icons.FeathersIcon_Archive",
    "arrow-down-circle" => "heaps.feathericons.icons.FeathersIcon_ArrowDownCircle",
    "arrow-down-left" => "heaps.feathericons.icons.FeathersIcon_ArrowDownLeft",
    "arrow-down-right" => "heaps.feathericons.icons.FeathersIcon_ArrowDownRight",
    "arrow-down" => "heaps.feathericons.icons.FeathersIcon_ArrowDown",
    "arrow-left-circle" => "heaps.feathericons.icons.FeathersIcon_ArrowLeftCircle",
    "arrow-left" => "heaps.feathericons.icons.FeathersIcon_ArrowLeft",
    "arrow-right-circle" => "heaps.feathericons.icons.FeathersIcon_ArrowRightCircle",
    "arrow-right" => "heaps.feathericons.icons.FeathersIcon_ArrowRight",
    "arrow-up-circle" => "heaps.feathericons.icons.FeathersIcon_ArrowUpCircle",
    "arrow-up-left" => "heaps.feathericons.icons.FeathersIcon_ArrowUpLeft",
    "arrow-up-right" => "heaps.feathericons.icons.FeathersIcon_ArrowUpRight",
    "arrow-up" => "heaps.feathericons.icons.FeathersIcon_ArrowUp",
    "at-sign" => "heaps.feathericons.icons.FeathersIcon_AtSign",
    "award" => "heaps.feathericons.icons.FeathersIcon_Award",
    "bar-chart-2" => "heaps.feathericons.icons.FeathersIcon_BarChart2",
    "bar-chart" => "heaps.feathericons.icons.FeathersIcon_BarChart",
    "battery-charging" => "heaps.feathericons.icons.FeathersIcon_BatteryCharging",
    "battery" => "heaps.feathericons.icons.FeathersIcon_Battery",
    "bell-off" => "heaps.feathericons.icons.FeathersIcon_BellOff",
    "bell" => "heaps.feathericons.icons.FeathersIcon_Bell",
    "bluetooth" => "heaps.feathericons.icons.FeathersIcon_Bluetooth",
    "bold" => "heaps.feathericons.icons.FeathersIcon_Bold",
    "book-open" => "heaps.feathericons.icons.FeathersIcon_BookOpen",
    "book" => "heaps.feathericons.icons.FeathersIcon_Book",
    "bookmark" => "heaps.feathericons.icons.FeathersIcon_Bookmark",
    "box" => "heaps.feathericons.icons.FeathersIcon_Box",
    "briefcase" => "heaps.feathericons.icons.FeathersIcon_Briefcase",
    "calendar" => "heaps.feathericons.icons.FeathersIcon_Calendar",
    "camera-off" => "heaps.feathericons.icons.FeathersIcon_CameraOff",
    "camera" => "heaps.feathericons.icons.FeathersIcon_Camera",
    "cast" => "heaps.feathericons.icons.FeathersIcon_Cast",
    "check-circle" => "heaps.feathericons.icons.FeathersIcon_CheckCircle",
    "check-square" => "heaps.feathericons.icons.FeathersIcon_CheckSquare",
    "check" => "heaps.feathericons.icons.FeathersIcon_Check",
    "chevron-down" => "heaps.feathericons.icons.FeathersIcon_ChevronDown",
    "chevron-left" => "heaps.feathericons.icons.FeathersIcon_ChevronLeft",
    "chevron-right" => "heaps.feathericons.icons.FeathersIcon_ChevronRight",
    "chevron-up" => "heaps.feathericons.icons.FeathersIcon_ChevronUp",
    "chevrons-down" => "heaps.feathericons.icons.FeathersIcon_ChevronsDown",
    "chevrons-left" => "heaps.feathericons.icons.FeathersIcon_ChevronsLeft",
    "chevrons-right" => "heaps.feathericons.icons.FeathersIcon_ChevronsRight",
    "chevrons-up" => "heaps.feathericons.icons.FeathersIcon_ChevronsUp",
    "chrome" => "heaps.feathericons.icons.FeathersIcon_Chrome",
    "circle" => "heaps.feathericons.icons.FeathersIcon_Circle",
    "clipboard" => "heaps.feathericons.icons.FeathersIcon_Clipboard",
    "clock" => "heaps.feathericons.icons.FeathersIcon_Clock",
    "cloud-drizzle" => "heaps.feathericons.icons.FeathersIcon_CloudDrizzle",
    "cloud-lightning" => "heaps.feathericons.icons.FeathersIcon_CloudLightning",
    "cloud-off" => "heaps.feathericons.icons.FeathersIcon_CloudOff",
    "cloud-rain" => "heaps.feathericons.icons.FeathersIcon_CloudRain",
    "cloud-snow" => "heaps.feathericons.icons.FeathersIcon_CloudSnow",
    "cloud" => "heaps.feathericons.icons.FeathersIcon_Cloud",
    "code" => "heaps.feathericons.icons.FeathersIcon_Code",
    "codepen" => "heaps.feathericons.icons.FeathersIcon_Codepen",
    "codesandbox" => "heaps.feathericons.icons.FeathersIcon_Codesandbox",
    "coffee" => "heaps.feathericons.icons.FeathersIcon_Coffee",
    "columns" => "heaps.feathericons.icons.FeathersIcon_Columns",
    "command" => "heaps.feathericons.icons.FeathersIcon_Command",
    "compass" => "heaps.feathericons.icons.FeathersIcon_Compass",
    "copy" => "heaps.feathericons.icons.FeathersIcon_Copy",
    "corner-down-left" => "heaps.feathericons.icons.FeathersIcon_CornerDownLeft",
    "corner-down-right" => "heaps.feathericons.icons.FeathersIcon_CornerDownRight",
    "corner-left-down" => "heaps.feathericons.icons.FeathersIcon_CornerLeftDown",
    "corner-left-up" => "heaps.feathericons.icons.FeathersIcon_CornerLeftUp",
    "corner-right-down" => "heaps.feathericons.icons.FeathersIcon_CornerRightDown",
    "corner-right-up" => "heaps.feathericons.icons.FeathersIcon_CornerRightUp",
    "corner-up-left" => "heaps.feathericons.icons.FeathersIcon_CornerUpLeft",
    "corner-up-right" => "heaps.feathericons.icons.FeathersIcon_CornerUpRight",
    "cpu" => "heaps.feathericons.icons.FeathersIcon_Cpu",
    "credit-card" => "heaps.feathericons.icons.FeathersIcon_CreditCard",
    "crop" => "heaps.feathericons.icons.FeathersIcon_Crop",
    "crosshair" => "heaps.feathericons.icons.FeathersIcon_Crosshair",
    "database" => "heaps.feathericons.icons.FeathersIcon_Database",
    "delete" => "heaps.feathericons.icons.FeathersIcon_Delete",
    "disc" => "heaps.feathericons.icons.FeathersIcon_Disc",
    "divide-circle" => "heaps.feathericons.icons.FeathersIcon_DivideCircle",
    "divide-square" => "heaps.feathericons.icons.FeathersIcon_DivideSquare",
    "divide" => "heaps.feathericons.icons.FeathersIcon_Divide",
    "dollar-sign" => "heaps.feathericons.icons.FeathersIcon_DollarSign",
    "download-cloud" => "heaps.feathericons.icons.FeathersIcon_DownloadCloud",
    "download" => "heaps.feathericons.icons.FeathersIcon_Download",
    "dribbble" => "heaps.feathericons.icons.FeathersIcon_Dribbble",
    "droplet" => "heaps.feathericons.icons.FeathersIcon_Droplet",
    "edit-2" => "heaps.feathericons.icons.FeathersIcon_Edit2",
    "edit-3" => "heaps.feathericons.icons.FeathersIcon_Edit3",
    "edit" => "heaps.feathericons.icons.FeathersIcon_Edit",
    "external-link" => "heaps.feathericons.icons.FeathersIcon_ExternalLink",
    "eye-off" => "heaps.feathericons.icons.FeathersIcon_EyeOff",
    "eye" => "heaps.feathericons.icons.FeathersIcon_Eye",
    "facebook" => "heaps.feathericons.icons.FeathersIcon_Facebook",
    "fast-forward" => "heaps.feathericons.icons.FeathersIcon_FastForward",
    "feather" => "heaps.feathericons.icons.FeathersIcon_Feather",
    "figma" => "heaps.feathericons.icons.FeathersIcon_Figma",
    "file-minus" => "heaps.feathericons.icons.FeathersIcon_FileMinus",
    "file-plus" => "heaps.feathericons.icons.FeathersIcon_FilePlus",
    "file-text" => "heaps.feathericons.icons.FeathersIcon_FileText",
    "file" => "heaps.feathericons.icons.FeathersIcon_File",
    "film" => "heaps.feathericons.icons.FeathersIcon_Film",
    "filter" => "heaps.feathericons.icons.FeathersIcon_Filter",
    "flag" => "heaps.feathericons.icons.FeathersIcon_Flag",
    "folder-minus" => "heaps.feathericons.icons.FeathersIcon_FolderMinus",
    "folder-plus" => "heaps.feathericons.icons.FeathersIcon_FolderPlus",
    "folder" => "heaps.feathericons.icons.FeathersIcon_Folder",
    "framer" => "heaps.feathericons.icons.FeathersIcon_Framer",
    "frown" => "heaps.feathericons.icons.FeathersIcon_Frown",
    "gift" => "heaps.feathericons.icons.FeathersIcon_Gift",
    "git-branch" => "heaps.feathericons.icons.FeathersIcon_GitBranch",
    "git-commit" => "heaps.feathericons.icons.FeathersIcon_GitCommit",
    "git-merge" => "heaps.feathericons.icons.FeathersIcon_GitMerge",
    "git-pull-request" => "heaps.feathericons.icons.FeathersIcon_GitPullRequest",
    "github" => "heaps.feathericons.icons.FeathersIcon_Github",
    "gitlab" => "heaps.feathericons.icons.FeathersIcon_Gitlab",
    "globe" => "heaps.feathericons.icons.FeathersIcon_Globe",
    "grid" => "heaps.feathericons.icons.FeathersIcon_Grid",
    "hard-drive" => "heaps.feathericons.icons.FeathersIcon_HardDrive",
    "hash" => "heaps.feathericons.icons.FeathersIcon_Hash",
    "headphones" => "heaps.feathericons.icons.FeathersIcon_Headphones",
    "heart" => "heaps.feathericons.icons.FeathersIcon_Heart",
    "help-circle" => "heaps.feathericons.icons.FeathersIcon_HelpCircle",
    "hexagon" => "heaps.feathericons.icons.FeathersIcon_Hexagon",
    "home" => "heaps.feathericons.icons.FeathersIcon_Home",
    "image" => "heaps.feathericons.icons.FeathersIcon_Image",
    "inbox" => "heaps.feathericons.icons.FeathersIcon_Inbox",
    "info" => "heaps.feathericons.icons.FeathersIcon_Info",
    "instagram" => "heaps.feathericons.icons.FeathersIcon_Instagram",
    "italic" => "heaps.feathericons.icons.FeathersIcon_Italic",
    "key" => "heaps.feathericons.icons.FeathersIcon_Key",
    "layers" => "heaps.feathericons.icons.FeathersIcon_Layers",
    "layout" => "heaps.feathericons.icons.FeathersIcon_Layout",
    "life-buoy" => "heaps.feathericons.icons.FeathersIcon_LifeBuoy",
    "link-2" => "heaps.feathericons.icons.FeathersIcon_Link2",
    "link" => "heaps.feathericons.icons.FeathersIcon_Link",
    "linkedin" => "heaps.feathericons.icons.FeathersIcon_Linkedin",
    "list" => "heaps.feathericons.icons.FeathersIcon_List",
    "loader" => "heaps.feathericons.icons.FeathersIcon_Loader",
    "lock" => "heaps.feathericons.icons.FeathersIcon_Lock",
    "log-in" => "heaps.feathericons.icons.FeathersIcon_LogIn",
    "log-out" => "heaps.feathericons.icons.FeathersIcon_LogOut",
    "mail" => "heaps.feathericons.icons.FeathersIcon_Mail",
    "map-pin" => "heaps.feathericons.icons.FeathersIcon_MapPin",
    "map" => "heaps.feathericons.icons.FeathersIcon_Map",
    "maximize-2" => "heaps.feathericons.icons.FeathersIcon_Maximize2",
    "maximize" => "heaps.feathericons.icons.FeathersIcon_Maximize",
    "meh" => "heaps.feathericons.icons.FeathersIcon_Meh",
    "menu" => "heaps.feathericons.icons.FeathersIcon_Menu",
    "message-circle" => "heaps.feathericons.icons.FeathersIcon_MessageCircle",
    "message-square" => "heaps.feathericons.icons.FeathersIcon_MessageSquare",
    "mic-off" => "heaps.feathericons.icons.FeathersIcon_MicOff",
    "mic" => "heaps.feathericons.icons.FeathersIcon_Mic",
    "minimize-2" => "heaps.feathericons.icons.FeathersIcon_Minimize2",
    "minimize" => "heaps.feathericons.icons.FeathersIcon_Minimize",
    "minus-circle" => "heaps.feathericons.icons.FeathersIcon_MinusCircle",
    "minus-square" => "heaps.feathericons.icons.FeathersIcon_MinusSquare",
    "minus" => "heaps.feathericons.icons.FeathersIcon_Minus",
    "monitor" => "heaps.feathericons.icons.FeathersIcon_Monitor",
    "moon" => "heaps.feathericons.icons.FeathersIcon_Moon",
    "more-horizontal" => "heaps.feathericons.icons.FeathersIcon_MoreHorizontal",
    "more-vertical" => "heaps.feathericons.icons.FeathersIcon_MoreVertical",
    "mouse-pointer" => "heaps.feathericons.icons.FeathersIcon_MousePointer",
    "move" => "heaps.feathericons.icons.FeathersIcon_Move",
    "music" => "heaps.feathericons.icons.FeathersIcon_Music",
    "navigation-2" => "heaps.feathericons.icons.FeathersIcon_Navigation2",
    "navigation" => "heaps.feathericons.icons.FeathersIcon_Navigation",
    "octagon" => "heaps.feathericons.icons.FeathersIcon_Octagon",
    "package" => "heaps.feathericons.icons.FeathersIcon_Package",
    "paperclip" => "heaps.feathericons.icons.FeathersIcon_Paperclip",
    "pause-circle" => "heaps.feathericons.icons.FeathersIcon_PauseCircle",
    "pause" => "heaps.feathericons.icons.FeathersIcon_Pause",
    "pen-tool" => "heaps.feathericons.icons.FeathersIcon_PenTool",
    "percent" => "heaps.feathericons.icons.FeathersIcon_Percent",
    "phone-call" => "heaps.feathericons.icons.FeathersIcon_PhoneCall",
    "phone-forwarded" => "heaps.feathericons.icons.FeathersIcon_PhoneForwarded",
    "phone-incoming" => "heaps.feathericons.icons.FeathersIcon_PhoneIncoming",
    "phone-missed" => "heaps.feathericons.icons.FeathersIcon_PhoneMissed",
    "phone-off" => "heaps.feathericons.icons.FeathersIcon_PhoneOff",
    "phone-outgoing" => "heaps.feathericons.icons.FeathersIcon_PhoneOutgoing",
    "phone" => "heaps.feathericons.icons.FeathersIcon_Phone",
    "pie-chart" => "heaps.feathericons.icons.FeathersIcon_PieChart",
    "play-circle" => "heaps.feathericons.icons.FeathersIcon_PlayCircle",
    "play" => "heaps.feathericons.icons.FeathersIcon_Play",
    "plus-circle" => "heaps.feathericons.icons.FeathersIcon_PlusCircle",
    "plus-square" => "heaps.feathericons.icons.FeathersIcon_PlusSquare",
    "plus" => "heaps.feathericons.icons.FeathersIcon_Plus",
    "pocket" => "heaps.feathericons.icons.FeathersIcon_Pocket",
    "power" => "heaps.feathericons.icons.FeathersIcon_Power",
    "printer" => "heaps.feathericons.icons.FeathersIcon_Printer",
    "radio" => "heaps.feathericons.icons.FeathersIcon_Radio",
    "refresh-ccw" => "heaps.feathericons.icons.FeathersIcon_RefreshCcw",
    "refresh-cw" => "heaps.feathericons.icons.FeathersIcon_RefreshCw",
    "repeat" => "heaps.feathericons.icons.FeathersIcon_Repeat",
    "rewind" => "heaps.feathericons.icons.FeathersIcon_Rewind",
    "rotate-ccw" => "heaps.feathericons.icons.FeathersIcon_RotateCcw",
    "rotate-cw" => "heaps.feathericons.icons.FeathersIcon_RotateCw",
    "rss" => "heaps.feathericons.icons.FeathersIcon_Rss",
    "save" => "heaps.feathericons.icons.FeathersIcon_Save",
    "scissors" => "heaps.feathericons.icons.FeathersIcon_Scissors",
    "search" => "heaps.feathericons.icons.FeathersIcon_Search",
    "send" => "heaps.feathericons.icons.FeathersIcon_Send",
    "server" => "heaps.feathericons.icons.FeathersIcon_Server",
    "settings" => "heaps.feathericons.icons.FeathersIcon_Settings",
    "share-2" => "heaps.feathericons.icons.FeathersIcon_Share2",
    "share" => "heaps.feathericons.icons.FeathersIcon_Share",
    "shield-off" => "heaps.feathericons.icons.FeathersIcon_ShieldOff",
    "shield" => "heaps.feathericons.icons.FeathersIcon_Shield",
    "shopping-bag" => "heaps.feathericons.icons.FeathersIcon_ShoppingBag",
    "shopping-cart" => "heaps.feathericons.icons.FeathersIcon_ShoppingCart",
    "shuffle" => "heaps.feathericons.icons.FeathersIcon_Shuffle",
    "sidebar" => "heaps.feathericons.icons.FeathersIcon_Sidebar",
    "skip-back" => "heaps.feathericons.icons.FeathersIcon_SkipBack",
    "skip-forward" => "heaps.feathericons.icons.FeathersIcon_SkipForward",
    "slack" => "heaps.feathericons.icons.FeathersIcon_Slack",
    "slash" => "heaps.feathericons.icons.FeathersIcon_Slash",
    "sliders" => "heaps.feathericons.icons.FeathersIcon_Sliders",
    "smartphone" => "heaps.feathericons.icons.FeathersIcon_Smartphone",
    "smile" => "heaps.feathericons.icons.FeathersIcon_Smile",
    "speaker" => "heaps.feathericons.icons.FeathersIcon_Speaker",
    "square" => "heaps.feathericons.icons.FeathersIcon_Square",
    "star" => "heaps.feathericons.icons.FeathersIcon_Star",
    "stop-circle" => "heaps.feathericons.icons.FeathersIcon_StopCircle",
    "sun" => "heaps.feathericons.icons.FeathersIcon_Sun",
    "sunrise" => "heaps.feathericons.icons.FeathersIcon_Sunrise",
    "sunset" => "heaps.feathericons.icons.FeathersIcon_Sunset",
    "table" => "heaps.feathericons.icons.FeathersIcon_Table",
    "tablet" => "heaps.feathericons.icons.FeathersIcon_Tablet",
    "tag" => "heaps.feathericons.icons.FeathersIcon_Tag",
    "target" => "heaps.feathericons.icons.FeathersIcon_Target",
    "terminal" => "heaps.feathericons.icons.FeathersIcon_Terminal",
    "thermometer" => "heaps.feathericons.icons.FeathersIcon_Thermometer",
    "thumbs-down" => "heaps.feathericons.icons.FeathersIcon_ThumbsDown",
    "thumbs-up" => "heaps.feathericons.icons.FeathersIcon_ThumbsUp",
    "toggle-left" => "heaps.feathericons.icons.FeathersIcon_ToggleLeft",
    "toggle-right" => "heaps.feathericons.icons.FeathersIcon_ToggleRight",
    "tool" => "heaps.feathericons.icons.FeathersIcon_Tool",
    "trash-2" => "heaps.feathericons.icons.FeathersIcon_Trash2",
    "trash" => "heaps.feathericons.icons.FeathersIcon_Trash",
    "trello" => "heaps.feathericons.icons.FeathersIcon_Trello",
    "trending-down" => "heaps.feathericons.icons.FeathersIcon_TrendingDown",
    "trending-up" => "heaps.feathericons.icons.FeathersIcon_TrendingUp",
    "triangle" => "heaps.feathericons.icons.FeathersIcon_Triangle",
    "truck" => "heaps.feathericons.icons.FeathersIcon_Truck",
    "tv" => "heaps.feathericons.icons.FeathersIcon_Tv",
    "twitch" => "heaps.feathericons.icons.FeathersIcon_Twitch",
    "twitter" => "heaps.feathericons.icons.FeathersIcon_Twitter",
    "type" => "heaps.feathericons.icons.FeathersIcon_Type",
    "umbrella" => "heaps.feathericons.icons.FeathersIcon_Umbrella",
    "underline" => "heaps.feathericons.icons.FeathersIcon_Underline",
    "unlock" => "heaps.feathericons.icons.FeathersIcon_Unlock",
    "upload-cloud" => "heaps.feathericons.icons.FeathersIcon_UploadCloud",
    "upload" => "heaps.feathericons.icons.FeathersIcon_Upload",
    "user-check" => "heaps.feathericons.icons.FeathersIcon_UserCheck",
    "user-minus" => "heaps.feathericons.icons.FeathersIcon_UserMinus",
    "user-plus" => "heaps.feathericons.icons.FeathersIcon_UserPlus",
    "user-x" => "heaps.feathericons.icons.FeathersIcon_UserX",
    "user" => "heaps.feathericons.icons.FeathersIcon_User",
    "users" => "heaps.feathericons.icons.FeathersIcon_Users",
    "video-off" => "heaps.feathericons.icons.FeathersIcon_VideoOff",
    "video" => "heaps.feathericons.icons.FeathersIcon_Video",
    "voicemail" => "heaps.feathericons.icons.FeathersIcon_Voicemail",
    "volume-1" => "heaps.feathericons.icons.FeathersIcon_Volume1",
    "volume-2" => "heaps.feathericons.icons.FeathersIcon_Volume2",
    "volume-x" => "heaps.feathericons.icons.FeathersIcon_VolumeX",
    "volume" => "heaps.feathericons.icons.FeathersIcon_Volume",
    "watch" => "heaps.feathericons.icons.FeathersIcon_Watch",
    "wifi-off" => "heaps.feathericons.icons.FeathersIcon_WifiOff",
    "wifi" => "heaps.feathericons.icons.FeathersIcon_Wifi",
    "wind" => "heaps.feathericons.icons.FeathersIcon_Wind",
    "x-circle" => "heaps.feathericons.icons.FeathersIcon_XCircle",
    "x-octagon" => "heaps.feathericons.icons.FeathersIcon_XOctagon",
    "x-square" => "heaps.feathericons.icons.FeathersIcon_XSquare",
    "x" => "heaps.feathericons.icons.FeathersIcon_X",
    "youtube" => "heaps.feathericons.icons.FeathersIcon_Youtube",
    "zap-off" => "heaps.feathericons.icons.FeathersIcon_ZapOff",
    "zap" => "heaps.feathericons.icons.FeathersIcon_Zap",
    "zoom-in" => "heaps.feathericons.icons.FeathersIcon_ZoomIn",
    "zoom-out" => "heaps.feathericons.icons.FeathersIcon_ZoomOut",
];
#end

class FeatherIcon {

    
    public static macro function resolve(iconExpr:Expr):Expr {
        var iconName: String = "";
        
        switch iconExpr.expr {
            case EConst(Constant.CString(s)): {
                iconName = s;
            }
            case EField(e, field, kind): {
                switch e.expr {
                    case EConst(CIdent("FeatherIcons")): {
                        iconName = FeatherIconsEnumFields2Id[field];
                    }
                    default:
                }
            }
            default: throw new haxe.macro.Error("Icon name incorrectly requested. Supply either a valid string or an enum instance in FeatherIcons", Context.currentPos());
        }

		var className = FeatherIconsString2Class.get(iconName);

		if (className == null) {
			throw new haxe.macro.Error("Icon class not found for " + iconName, Context.currentPos());
		}

        var pack = className.split(".");
        var name = pack[pack.length - 1];
        pack.splice(pack.length - 1, 1);

        var newExpr:Expr = {
            pos: Context.currentPos(),
            expr: ENew({pack: pack, name: name}, [])
        }

		return macro FeatherIcon.from(${newExpr});
	}


    #if !macro
    var store:GraphicsStore;
    public var unitSize: Int = 1;
    public var strokeWidth: Int = 2;
    public var color: Int = 0xFFFFFF;

    private function new() {
        
    }

	public static function from(store:GraphicsStore):FeatherIcon {
        var icon = new FeatherIcon();
        icon.store = store;
        return icon;
	}

	public function toGraphics():h2d.Graphics {
        var g = new h2d.Graphics();
		GraphicsCommandExecute.draw(g, store.getStrokes(), [LineWidth(strokeWidth), UnitSize(unitSize), LineColor(color)]);
        return g;
	}

    #end

}